
logging.level:
  org.springframework.security: DEBUG
  org.springframework.security.oauth2: DEBUG
  org.springframeowork.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9000