server:
  port: 8765

logging.level:
  org.springframework.cloud.gateway: WARN
  org.springframework.security: TRACE
  org.springframework.security.oauth2: TRACE
  org.springframework.web: INFO

spring:

  cloud:

    gateway:

      default-filters:
        - TokenRelay=

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET

      routes:
        - id: pivmart-main
          uri: lb://pivmart-main
          predicates:
            - Path=/api/products,/api/products/**,/api/catalogs,/api/catalogs/**
        - id: pivmart-cart-api
          uri: lb://pivmart-cart-api
          predicates:
            - Path=/api/cart,/api/cart/**
          filters:
            - SecureHeaders=
        - id:  purchase-api
          uri: lb://pivmart-purchase-api
          predicates:
            - Path=/api/purchases,/api/purchases/**
          filters:
            - SecureHeaders=
        - id: pivmart-ui
          uri: http://localhost:3000
          predicates:
            - Path=/**

  security:

    oauth2:

      client:

        registration:

          pivmart:
            provider: keycloak
            client-id: pivmart
            client-secret: 77639fd7-a70c-4126-8816-a7d19a1942d0
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,roles,profile,email,user.purchases,user.cart

        provider:

          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/master

#cf bind-service pivmart-main pivmart-gateway -c '{ "routes": [{"uri": "lb://pivmart-main.apps.internal", "predicates": ["Path=/api/products/**,/api/catalogs/**"], "filters": ["StripPrefix=0"]}] }'
#cf bind-service catalog-browser-pivmart pivmart-gateway -c '{ "routes": [{"uri": "lb://catalog-browser-pivmart.apps.internal", "order": 100, "predicates": ["Path=/**"], "filters": ["StripPrefix=0"]}] }'
#cf bind-service cart-api pivmart-gateway -c '{ "routes": [{"uri": "lb://cart-api.apps.internal", "predicates": ["Path=/api/cart/**"], "filters": ["StripPrefix=0"]}] }'
#cf bind-service purchase-api pivmart-gateway -c '{ "routes": [{"uri": "lb://purchase-api.apps.internal", "predicates": ["Path=/api/purchases/**"], "filters": ["StripPrefix=0"]}] }'

#---
#spring:
#  profiles: cloud
#  cloud:
#    gateway:
#      routes:
#        - id: pivmart-api
#          uri: lb://pivmart
#          predicates:
#            - Path=/api/products/**,/api/catalogs/**
#        - id: cart-api
#          uri: lb://cart-api
#          predicates:
#            - Path=/api/cart/**
#        - id:  purchase-api
#          uri: lb://purchase-api
#          predicates:
#            - Path=/api/purchases/**
#        - id: pivmart-ui
#          uri: http://pivmart-ui.apps.internal
#          predicates:
#            - Path=/**
#