
server:
  port: 8083

logging:
  level:
    org.springframework.cloud.stream: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.web: debug

spring:
  cloud:
    stream:
      source: cartPublisher
      bindings:
        cartPublisher-out-0:
          destination: cart-exchange
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
