server:
  port: 8083

logging:
  level:
    org.springframework.web: debug
    org.springframework.cloud.stream: debug

spring:
  cloud:
    stream:
      source: cartPublisher
      bindings:
        cartPublisher-out-0:
          destination: cart-exchange