---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: adoptopenjdk/openjdk11
    tag: latest
inputs:
  - name: src-repo
outputs:
  - name: artifacts
params:
  BUILD_CMD: ./gradlew clean build
  COPY_CMD: cp build/libs/pivmart-*-SNAPSHOT.jar ../../artifacts/pivmart.jar
run:
  path: src-repo/pivmart/ci/scripts/build.sh