server:
  port: 8084

logging:
  level:
    org.springframework.web: debug

spring:
  cloud:
    stream:
      bindings:
        checkoutListener-in-0:
          destination: cart-exchange
          group: purchase-api

workshop:
  prefix: ${WS_PREFIX:pivmart}